### ISSUE TITLE
Unable to Run Castlemock on top of Openshift

### ISSUE THREAD

**Issue by edwin** [castlemock/castlemock#152]
**Describe the bug**
As the title describe, im running castlemock on top of docker and deployed it on Openshift. It gives this error,

```
Caused by: java.lang.IllegalStateException: Unable to create the following folder: ?/.castlemock/graphql/attribute/v1
--
  | at com.castlemock.repository.core.file.FileRepositorySupport.createDirectory(FileRepositorySupport.java:186)
  | at com.castlemock.repository.core.file.FileRepositorySupport.load(FileRepositorySupport.java:94)
  | at com.castlemock.repository.core.file.FileRepository.loadFiles(FileRepository.java:382)
  | at com.castlemock.repository.core.file.FileRepository.initialize(FileRepository.java:105)
  | at com.castlemock.repository.core.file.FileRepository$$FastClassBySpringCGLIB$$a62f64ae.invoke(<generated>)
  | at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

Perhaps issue happen because by default, Openshift gives a random userid as enforced by its default security policy.  And somehow Castlemock is unable to create a default filesystem folder due to it.

Question : Is there any way to make filesystem's folder location configurable?

**To Reproduce**
1. Go to manage.openshift.com, or install your own openshift using OKD
2. Create a simple dockerfile,
```
FROM openjdk:8-jdk-stretch

ARG TOMCAT_VERSION=8.5.47

RUN mkdir /tomcat
RUN curl --silent --location --retry 3 "https://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz" | gunzip | tar x -C /tomcat/ 

RUN mv /tomcat/apache-* /tomcat/tomcat

ENV CATALINA_HOME /tomcat/tomcat

RUN curl -o castlemock.war -fSL https://github.com/castlemock/castlemock/releases/download/1.40/castlemock.war
RUN cp castlemock.war /tomcat/tomcat/webapps 

RUN useradd jboss -g 0 
RUN usermod -g root -G 0 jboss && mkdir /home/jboss 
RUN chown -R jboss:0 /tomcat/tomcat && chown -R jboss:0 /home/jboss

CMD ["/tomcat/tomcat/bin/catalina.sh", "run"]

# Expose HTTP port 8080
EXPOSE 8080

USER jboss
```
3. Tag and push to dockerhub, and pull to Openshift
4. Exception happens

**Expected behavior**
App runs successfully

**Comment by edwin** [comment]
yups, got the root cause,

`base.file.directory=${user.home}/.castlemock`

[https://github.com/castlemock/castlemock/blob/master/app/src/main/resources/file-repository.properties#L5](url)

injecting base.file.directory on tomcat runtime directly solve my problem,
```
FROM openjdk:8-jdk-stretch

ARG TOMCAT_VERSION=8.5.47

RUN mkdir /tomcat
RUN curl --silent --location --retry 3 "https://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz" | gunzip | tar x -C /tomcat/ 

RUN mv /tomcat/apache-* /tomcat/tomcat

ENV CATALINA_HOME /tomcat/tomcat

RUN curl -o castlemock.war -fSL https://github.com/castlemock/castlemock/releases/download/1.40/castlemock.war
RUN cp castlemock.war /tomcat/tomcat/webapps 

RUN useradd jboss -g 0 
RUN usermod -g root -G 0 jboss && mkdir /home/jboss 
RUN chown -R jboss:0 /tomcat/tomcat && chown -R jboss:0 /home/jboss
RUN mkdir /tomcat/castlemock && chown -R jboss:0 /tomcat/castlemock

# inject env variable here to override base.file.directory configuration
RUN touch /tomcat/tomcat/bin/setenv.sh && echo "export CATALINA_OPTS=\"$CATALINA_OPTS -Dbase.file.directory=/tomcat/castlemock \"" > /tomcat/tomcat/bin/setenv.sh

CMD ["/tomcat/tomcat/bin/catalina.sh", "run"]

# Expose HTTP port 8080
EXPOSE 8080

USER jboss
```

😄

**Comment by mhewedy** [comment]
I just want to add a couple of things, 
You can base your docker find on [castlemock ](https://hub.docker.com/r/castlemock/castlemock/)image
And, there's a MongoDB support you might need to use for cluster environment

**Comment by edwin** [comment]
hi @mhewedy 
yes you are correct. For most cases, extending castlemock image is sufficient enough
