### ISSUE TITLE
ERROR: com.castlemock.web.basis.support.HttpMessageSupport - Error occurred when extracting HTTP response body

### ISSUE THREAD

**Issue by GrumpyMeow** [castlemock/castlemock#153]
Hi,

I use CastleMock to isolate my containerized environment from testing-environments. I do this with forwarding webapi requests from a containerized application to a testing-environment. This works quite well for most of the WebApi's until now.

on a specific WebApi i get the following exception:
```
ERROR: com.castlemock.web.basis.support.HttpMessageSupport - Error occurred when extracting HTTP response body
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at com.castlemock.web.basis.support.HttpMessageSupport.extractHttpBody(HttpMessageSupport.java:293)
	at com.castlemock.web.mock.rest.web.mock.controller.AbstractRestServiceController.forwardRequest(AbstractRestServiceController.java:276)
	at com.castlemock.web.mock.rest.web.mock.controller.AbstractRestServiceController.process(AbstractRestServiceController.java:192)
	at com.castlemock.web.mock.rest.web.mock.controller.AbstractRestServiceController.process(AbstractRestServiceController.java:126)
	at com.castlemock.web.mock.rest.web.mock.controller.RestServiceController.postMethod(RestServiceController.java:84)
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

I suspect it has to do with a specific response-headers to be present:
```
HTTP/1.1 201 Created
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 776
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
Access-Control-Allow-Origin: https://acc-www.xxxxxxxxxx.local
X-AspNet-Version: 4.0.30319
Request-Context: appId=cid-v1:b6dae7f9-4659-4add-a5b9-2f5666f57106
Access-Control-Expose-Headers: Request-Context
Access-Control-Allow-Headers: Authorization
Date: Tue, 19 Nov 2019 14:21:31 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
Connection: Keep-Alive
Set-Cookie: BC_HA_XXXXXXXXXXXXXX_13087056=XXXXXXXXX; Domain=.xxxxxxxxx.local; expires=Tue, 19-Nov-19 14:51:32 GMT; Path=/

{"XXXXXEndpoint":"https://xxxxxxxxxxxxxxxxxxxxxxxx/processing","Fields":{"txntype":"sale","timezone":"Europe","txndatetime":"2019:11:19-15:21:31","hash_algorithm":"SHA256","hash":"xxxxxxxxxxxxxxxxxxxxx","storename":"xxxxxxxxxxxx","mode":"payonly","chargetotal":"1.00","currency":"978","oid":"XxxxxxxxxXXXX20191119-00014","paymentMethod":"xxxxxxxxx","responseSuccessURL":"https://acc-api.xxxxxxxxxxxxx.xxxxxx/xxxxxxxxxxxxx.WebApi/api/v1/xxxxx/update","responseFailURL":"https://acc-api.xxxxxxxxxxxx.xxxxxxx/xxxxxxxxxxx.WebApi/api/v1/xxxxx/update","source":"XxxxxxxxDIP","succesRedirectUrl":"","failRedirectUrl":"","cancelRedirectUrl":"","uncertainRedirectUrl":"","comments":"Lastname 'Tester' - EmailAddress 'test@xxxxxxxxx.local'"}}
```

**Comment by GrumpyMeow** [comment]
I think the issue is that "characterEncoding" is null.
```
else {
                // No encoding was used. Simply parse the response.
                final InputStreamReader inputStreamReader = new InputStreamReader(inputStream, characterEncoding);
                bufferedReader = new BufferedReader(inputStreamReader);
            }
```

**Comment by GrumpyMeow** [comment]
#154
