### ISSUE TITLE
Error while importing YAML & Json Swagger files: Unable to parse the Swagger content

### ISSUE THREAD

**Issue by abdulazizfmw** [castlemock/castlemock#649]
**Describe the bug**
Error while importing YAML & Json Swagger files: Unable to parse the Swagger content

**To Reproduce**
1. Create a new Rest Project
2. Upload Swagger file from computer
3. See error

```java
2023-07-18 12:19:06 java.lang.IllegalArgumentException: Unable to parse the Swagger content.
2023-07-18 12:19:06     at com.castlemock.service.mock.rest.project.converter.swagger.SwaggerRestDefinitionConverter.convertSwagger(SwaggerRestDefinitionConverter.java:158) ~[service-mock-rest-1.63.jar:?]
2023-07-18 12:19:06     at com.castlemock.service.mock.rest.project.converter.swagger.SwaggerRestDefinitionConverter.convert(SwaggerRestDefinitionConverter.java:121) ~[service-mock-rest-1.63.jar:?]
2023-07-18 12:19:06     at com.castlemock.service.mock.rest.project.ImportRestDefinitionService.process(ImportRestDefinitionService.java:74) ~[service-mock-rest-1.63.jar:?]
2023-07-18 12:19:06     at com.castlemock.service.core.ServiceProcessorImpl.process(ServiceProcessorImpl.java:85) ~[service-core-1.63.jar:?]
2023-07-18 12:19:06     at jdk.internal.reflect.GeneratedMethodAccessor131.invoke(Unknown Source) ~[?:?]
``` 

**Expected behavior**
File imported and generate the mock

**Screenshots**
Swagger files are valid:
<img width="485" alt="image" src="https://github.com/castlemock/castlemock/assets/125686319/126c4b23-cf70-46be-ab9f-566096b458ff">

<img width="515" alt="image" src="https://github.com/castlemock/castlemock/assets/125686319/3c3e65d7-86fe-481a-a063-cdab4d655a01">

**Castle Mock**
 - Version 1.63
 - Java Version 11.0.14.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by abdulazizfmw** [comment]
Same issue with the latest Docker image 1.65
