### ISSUE TITLE
Unable to import Swagger link: Unable to parse the Swagger content.

### ISSUE THREAD

**Issue by abdulazizfmw** [castlemock/castlemock#650]
**Describe the bug**
Unable to import Swagger link: Unable to parse the Swagger content.

**To Reproduce**
1. Create a new Project
2. Import swagger by Link : https://petstore.swagger.io/#/
3. See error
```java
2023-07-18 12:39:20 java.lang.IllegalArgumentException: Unable to parse the Swagger content.
2023-07-18 12:39:20     at com.castlemock.service.mock.rest.project.converter.swagger.SwaggerRestDefinitionConverter.convertSwagger(SwaggerRestDefinitionConverter.java:158) ~[service-mock-rest-1.63.jar:?]
2023-07-18 12:39:20     at com.castlemock.service.mock.rest.project.converter.swagger.SwaggerRestDefinitionConverter.convert(SwaggerRestDefinitionConverter.java:135) ~[service-mock-rest-1.63.jar:?]
2023-07-18 12:39:20     at com.castlemock.service.mock.rest.project.ImportRestDefinitionService.process(ImportRestDefinitionService.java:67) ~[service-mock-rest-1.63.jar:?]
2023-07-18 12:39:20     at com.castlemock.service.core.ServiceProcessorImpl.process(ServiceProcessorImpl.java:85) ~[service-core-1.63.jar:?]
``` 

**Expected behavior**
Swagger imported and generate the mock

**Screenshots**
Valid swagger link
https://petstore.swagger.io/#/
<img width="366" alt="image" src="https://github.com/castlemock/castlemock/assets/125686319/2d42872d-a502-4771-b9cc-740c1398ad8b">

### Note: the mock generated by uploading the swagger file:
<img width="401" alt="image" src="https://github.com/castlemock/castlemock/assets/125686319/3ce77c8e-0b4d-43db-aa92-eb10db30f367">

**Castle Mock**
 - Version 1.63
 - Java Version 11

**Comment by abdulazizfmw** [comment]
Same issue with the latest Docker image 1.65

**Comment by abdulazizfmw** [comment]
Thanks
It is working
