### ISSUE TITLE
"ReferenceError: arguments is not defined" in react-bootstrap-table2-toolkit

### ISSUE THREAD

**Issue by loic-brtd** [castlemock/castlemock#710]
**Describe the bug**
Hi! I was trying to build and start CastleMock locally on my machine but I encountered a JS error when opening my browser on http://localhost:3000 : 

```
SearchBar.js:9 Uncaught ReferenceError: arguments is not defined
    at ./node_modules/react-bootstrap-table2-toolkit/lib/src/search/SearchBar.js (SearchBar.js:9:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/react-bootstrap-table2-toolkit/lib/src/search/index.js (index.js:7:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/react-bootstrap-table2-toolkit/lib/index.js (index.js:8:1)
    at options.factory (react refresh:6:1)
```

**To Reproduce**
```sh
git clone git@github.com:castlemock/castlemock.git # I actually made a fork and then cloned the fork
cd castlemock/
cd web/web-frontend/
yarn install
yarn start # opens my browser on http://localhost:3000
# Open the javascript console in the dev tools to see the stack trace mentioned above
```

**Expected behavior**
I expect the homepage (or login page) of CastleMock to appear with no error.

**Castle Mock**
 - Version 1.65 (root pom.xml version, master branch, commit b65a95587af0b2102a78c474ea96423350aeae4d)
 - Node Version v20.11.0
 - Yarn version 1.22.21
 - Java Version 21 (not used to reproduce this bug)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro (5.10.205-1-MANJARO)
 - Browser: Google Chrome (119.0.6045.199)

**Additional context:**
This error is related to this issue https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1520, so it doesn't seem to be a bug from CastleMock itself but from a dependency. However, I'm wondering if anyone has encountered this when working on CastleMock and if so, is there a workaround or a fix I can use? Thanks.

**Comment by christopher1986** [comment]
I was able to get the frontend working by using `react-app-rewired` which allows tweaking of webpack config(s) without using 'eject'. I installed this dependency using `yarn add react-app-rewired --dev`. The following changes were (also) necessary:

**web/web-frontend/config-overrides.js**
```js
module.exports = function override(config, env) {
    const resolve = config.resolve ?? {};

    config.resolve = {
        ...resolve,
        alias: {
            ...config.resolve.alias,
            'react-bootstrap-table2-toolkit': `react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.js`,
            'react-bootstrap-table2-toolkit-css': `react-bootstrap-table2-toolkit/../react-bootstrap-table2-toolkit.css`,
        }
    }

    return config;
}
```

**web/web-frontend/package.json**
```json
"scripts": {
    "start": "react-app-rewired start --scripts-version  react-scripts",
    "build": "react-app-rewired build --scripts-version  react-scripts",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject"
},
```

**web/web-frontend/App.js**
```js
import 'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.min.css';
import 'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.min.js';
```

**to:**
```js
import 'react-bootstrap-table2-toolkit-css';
import 'react-bootstrap-table2-toolkit';
```

The solution above is inspired by the comments regarding [pull request #1502](https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/1506) from react-bootstrap-table2. What I can't figure out is why this pull request is still open after 5 years.
