### ISSUE TITLE
Import WSDL throws an exception

### ISSUE THREAD

**Issue by vutran-info** [castlemock/castlemock#748]
**Describe the bug**
When I try to import WSDL file in a SOAP project, I got an exception:
```
2024-04-10 14:50:35 2024-04-10 07:50:35.406 ERROR 1 --- [nio-8080-exec-5] o.s.b.w.s.s.ErrorPageFilter              : Forwarding to error page from request [/api/rest/soap/project/OXcdlD/wsdl/link] due to exception [Unable to parse the WSDL file]
2024-04-10 14:50:35 
2024-04-10 14:50:35 java.lang.IllegalStateException: Unable to parse the WSDL file
2024-04-10 14:50:35     at com.castlemock.service.mock.soap.project.CreateSoapPortsService.process(CreateSoapPortsService.java:70) ~[service-mock-soap-1.65.jar:?]
2024-04-10 14:50:35     at com.castlemock.service.core.ServiceProcessorImpl.process(ServiceProcessorImpl.java:85) ~[service-core-1.65.jar:?]
2024-04-10 14:50:35     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
2024-04-10 14:50:35     at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
2024-04-10 14:50:35     at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at jdk.proxy3.$Proxy82.process(Unknown Source) ~[?:?]
2024-04-10 14:50:35     at com.castlemock.web.mock.soap.controller.rest.SoapProjectRestController.linkWSDL(SoapProjectRestController.java:155) ~[web-mock-soap-1.65.jar:?]
2024-04-10 14:50:35     at com.castlemock.web.mock.soap.controller.rest.SoapProjectRestController$$FastClassBySpringCGLIB$$9891fade.invoke(<generated>) ~[web-mock-soap-1.65.jar:?]
2024-04-10 14:50:35     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:67) ~[spring-security-core-5.8.3.jar:5.8.3]
2024-04-10 14:50:35     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at com.castlemock.web.mock.soap.controller.rest.SoapProjectRestController$$EnhancerBySpringCGLIB$$68bb5a46.linkWSDL(<generated>) ~[web-mock-soap-1.65.jar:?]
2024-04-10 14:50:35     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
2024-04-10 14:50:35     at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
2024-04-10 14:50:35     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-04-10 14:50:35     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.27.jar:5.3.27]
```

**To Reproduce**
1. Go to SOAP project
2. Click on Upload WSDL
<img width="718" alt="image" src="https://github.com/castlemock/castlemock/assets/82991673/3f077788-3af1-40f3-9abe-fa6e1b790861">
3. See error

**Expected behavior**

**Screenshots**
<img width="448" alt="image" src="https://github.com/castlemock/castlemock/assets/82991673/9bbc15d5-3fb4-448e-80ae-d8216480e39f">

**Castle Mock**
 - Version 1.67
 - Java Version 21.0.2

**WSDL files or other resource attachments:** Please read our FAQ before submitting or reference any WSDL files or other resources: [FAQ](https://github.com/castlemock/castlemock/wiki/FAQ)
[castle-mock-error.log](https://github.com/castlemock/castlemock/files/14929481/castle-mock-error.log)

**Comment by viniciusxyz** [comment]
@vutran-info Can you add an example WSDL? I just followed this same flow with the same version and it's working
